######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 11 21:00:00 2014
######################################################################

# Modified by moehuster
TEMPLATE = app
INCLUDEPATH += ../../include ..
HEADERS += dms_client.h mythread.h ../logreader.h ../logsender.h
SOURCES += dms_client.cpp mythread.cpp client_qt.cpp \
           ../logreader.cpp ../logsender.cpp
