######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 11 21:00:00 2014
######################################################################

# Modified by moehuster
TEMPLATE = app
HEADERS += dms_client.h
SOURCES += dms_client.cpp client_test.cpp
